name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Time
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
        echo "title=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build-Dependent
      run: |
        dotnet publish WorkbenchToolkit/WorkbenchToolkit.csproj -r win-x86 --self-contained false
        dotnet publish WorkbenchToolkit/WorkbenchToolkit.csproj -r win-x64 --self-contained false
    - name: Rename-Dependent
      run: |
        mv ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.exe ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.win.x86.exe
        mv ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.exe ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.win.x64.exe
    - name: Build-Independence
      run: |
        dotnet publish WorkbenchToolkit/WorkbenchToolkit.csproj -r win-x86 --self-contained true
        dotnet publish WorkbenchToolkit/WorkbenchToolkit.csproj -r win-x64 --self-contained true
    - name: Rename-Independence
      run: |
        mv ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.exe ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.alone.win.x86.exe
        mv ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.exe ./WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.alone.win.x64.exe
    - name: Publish
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.TOKEN }}"
        title: "v${{ steps.date.outputs.title }}"
        automatic_release_tag: "AutoRelease-${{ steps.date.outputs.date }}"
        prerelease: true
        files: |
          WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.win.x86.exe
          WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.win.x64.exe
          WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x86/publish/WorkbenchToolkit.alone.win.x86.exe
          WorkbenchToolkit/bin/Release/net8.0-windows10.0.17763.0/win-x64/publish/WorkbenchToolkit.alone.win.x64.exe
        